### ISSUE TITLE
Java NullPointerException

### ISSUE THREAD

**Issue by Technodad** [robertvandervoort/SmartThings#1]
First, thinks for digging into the Aeon Multisensor 6 while Smartthings is catching up.

I have installed the code. However, I'm getting an error in both the simulator and in when I test in the IDE with the actual device:

java.lang.NullPointerException: Cannot invoke method toByteArray() on null object @ line 280

This error also keeps me from setting the device type in "My Devices". 

As near as I can tell, there isn't an explicit toByteArray call in the code - must be something getting passed in.

**Comment by robertvandervoort** [comment]
Hey there. Yep, I've changed it a lot but haven't committed it. This was just the first stab at it. It should ad least and work to some degree though... I'll put up some new code soon. I've been going back and forth with their engineering folks trying to figure out why the UV isn't working and it turns out reporting for it was turned off by default and their documentation isn't really complete...

**Comment by prune998** [comment]
Sorry to ask, but as of today, what is the difference between your version of the "driver" for the multisensor 6 and the one bundled within Smartthings ? 

thanks

**Comment by robertvandervoort** [comment]
The difference is the one that comes with smartthings doesn't allow you to change any of the settings in the device preferences like sensor offsets or reporting interval. Mine also allows you to do as quick as 5 minute updates while on battery while the shipped version only allows 1 hour intervals. Also, I show UV and tamper detection on the device page in the app and theirs does not. My tamper detection also resets after 20 seconds while theirs never resets.

I will be adding more functionality soon. For future discussion, see the thread on SmartThing forums. https://community.smartthings.com/t/aeotech-multisensor-6-gen-5-zwave-plus-model-zw100-a
